### ISSUE TITLE
The arxiv paper links to nowhere.

### ISSUE THREAD

**Issue by zhimin-z** [CMMMU-Benchmark/CMMMU#1]
Clicking on this option will redirect you to the main page of Arxiv...
![image](https://github.com/CMMMU-Benchmark/CMMMU/assets/8592144/bf73b975-cda1-429c-96c0-488df3841614)

**Comment by zhimin-z** [comment]
Same to the GitHub main page:
![image](https://github.com/CMMMU-Benchmark/CMMMU/assets/8592144/4b7870d4-82b4-4c39-9a87-f32a0c75c122)
![image](https://github.com/CMMMU-Benchmark/CMMMU/assets/8592144/03537a59-ec5d-49a4-9c8e-f8e7ee546109)

**Comment by CMMMU-Benchmark** [comment]
Hi,

Apologies for any inconvenience caused. 
We have now corrected the arXiv link, and you can access the correct URL by clicking the option. 
Thank you for bringing this issue to our attention.
