### ISSUE TITLE
Paper is not found in the Hugging Face...

### ISSUE THREAD

**Issue by zhimin-z** [CMMMU-Benchmark/CMMMU#3]
![image](https://github.com/CMMMU-Benchmark/CMMMU/assets/8592144/ee482f11-5611-439c-b43f-ca13a900ba2f)
Clicking on the [linkage](https://huggingface.co/papers/index?arxivId=2401.20847) but found:
![image](https://github.com/CMMMU-Benchmark/CMMMU/assets/8592144/ac3fe7a9-7643-4806-be9d-3bd11b9d78a6)

**Comment by CMMMU-Benchmark** [comment]
Hi,

Apologies for any inconvenience caused.
We have now corrected the huggingface paper link, and you can access the correct URL by clicking the option.
Thank you for bringing this issue to our attention.

Best, 
CMMMU Team
